---

  #- name: Disable UAC
  #  win_shell: New-ItemProperty -Path HKLM:Software\Microsoft\Windows\CurrentVersion\policies\system -Name EnableLUA -PropertyType DWord -Value 0 -Force

  #- name: Reboot Server
  #  win_reboot:
  #    shutdown_timeout_sec: 3600
  #    reboot_timeout_sec: 3600

  - name: Download Tomcat
    win_get_url:
        url: "{{tomcat_zip_download}}"
        dest: C:\Apps\tomcat.zip

  - name: Extract Tomcat
    win_unzip:
        src: C:\Apps\tomcat.zip
        dest: "C:\\tomcat"
        creates: "C:\\tomcat\\apache-tomcat-8.5.15"

  - name: Set tomcat users
    win_template:
      src: "{{playbook_dir}}/templates/tomcat/tomcat-users.xml"
      dest: "C:\\tomcat\\apache-tomcat-8.5.15\\conf\\tomcat-users.xml"

  - name: Set tomcat server settings
    win_template:
      src: "{{playbook_dir}}/templates/tomcat/server.xml"
      dest: "C:\\tomcat\\apache-tomcat-8.5.15\\conf\\server.xml"

  - name: Allow manager to be used anywhere
    win_template:
      src: "{{playbook_dir}}/templates/tomcat/context.xml"
      dest: "C:\\tomcat\\apache-tomcat-8.5.15\\webapps\\manager\\META-INF\\context.xml"

  - name: Install Tomcat Service
    win_shell: "C:\\tomcat\\apache-tomcat-8.5.15\\bin\\service.bat install Tomcat8"
    args:
      chdir: "C:\\tomcat\\apache-tomcat-8.5.15\\bin"

  - name: Start Tomcat Service
    win_service:
      name: "Tomcat8"
      state: started
      start_mode: auto
    ignore_errors: yes

  - name: Add Tomcat Shortcut
    win_shortcut:
      src: '%PROGRAMFILES(x86)%\Google\Chrome\Application\chrome.exe'
      dest: '%PUBLIC%\Desktop\Tomcat.lnk'
      args: '--new-window http://localhost:38080/'
      directory: '%PROGRAMFILES(x86)%\Google\Chrome\Application'
      icon: '%PROGRAMFILES(x86)%\Google\Chrome\Application\chrome.exe,0'