---

  - name: Assume AWS Role
    sts_assume_role:
      role_arn: "arn:aws:iam::968802670493:role/AnsibleWorker"
      role_session_name: "AnsibleBuild"
      region: "{{region}}"
    register: assumed_role

  - name: Create Windows Server
    ec2:
      aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
      aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
      security_token: "{{ assumed_role.sts_creds.session_token }}"
      key_name: OctopusVirginia
      instance_type: m3.2xlarge
      image: "{{win_ami}}"
      instance_profile_name: ListEC2
      wait: yes
      wait_timeout: 600
      group: WildFlyTomcat
      count: "{{server_count}}"
      region: "{{region}}"
      user_data: "{{ lookup('template', 'templates/userdata.txt.j2') }}"
      volumes:
        - device_name: /dev/sda1
          volume_size: 80
          volume_type: gp2
          delete_on_termination: true
      instance_tags:
        Appplication: OctopusDeploy
        Domain: None
        Environment: Test
        LifeTime: Permanent
        Name: Octopus Deploy
        OwnerContact: "@matthew.casperson"
        Source: Ansible
    register: windows_server_ec2

  - name: Add Host to Inventory
    add_host:
      name: "{{ item.public_ip }}"
      groups:
        - windows_server
        - java_server
      instance_id: "{{ item.id }}"
      aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
      aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
      security_token: "{{ assumed_role.sts_creds.session_token }}"
      region: "{{ region }}"
    with_items: "{{windows_server_ec2.instances}}"

  - name: Wait for WinRM to answer on all hosts
    wait_for:
      port: 5986
      host: "{{ item.public_ip }}"
      timeout: 6000
    with_items: "{{windows_server_ec2.instances}}"