---

  - name: Create Windows Server
    ec2:
      key_name: OctopusVirginia
      instance_type: m3.xlarge
      image: "{{win_ami}}"
      wait: yes
      wait_timeout: 600
      group: OctopusHttp
      count: 1
      region: us-east-1
      user_data: "{{ lookup('template', 'templates/userdata.txt.j2') }}"
      volumes:
        - device_name: /dev/sda1
          volume_size: 80
          volume_type: gp2
      instance_tags:
        Appplication: OctopusDeploy
        Domain: None
        Environment: Test
        LifeTime: Permanent
        Name: Octopus Deploy
        OwnerContact: "@matthew.casperson"
        Source: Ansible
    register: windows_server_ec2

  - name: Add Host to Inventory
    add_host:
      name: "{{ windows_server_ec2.instances[0].public_ip }}"
      groups: windows_server

  - name: Wait for WinRM to answer on all hosts
    wait_for:
      port: 5986
      host: "{{ windows_server_ec2.instances[0].public_ip }}"
      timeout: 600