---

  - name: download bamboo 5
    get_url:
        url: "{{bamboo5_download}}"
        dest: /tmp/bamboo.tar.gz
        mode: 0440

  - name: extract bamboo
    unarchive:
        src: /tmp/bamboo.tar.gz
        dest: /opt
        copy: no

  - name: create plugins directory
    file:
        path: "/opt/{{bamboo5_directory}}/plugins"
        state: directory

  - name: set bamboo permissions
    file:
      state: directory
      path: "/opt/{{bamboo5_directory}}"
      owner: "{{bamboo_user}}"
      group: "{{bamboo_user}}"
      recurse: true

  - name: Fix up bamboo 5 home
    lineinfile:
      dest: "/opt/{{bamboo5_directory}}/atlassian-bamboo/WEB-INF/classes/bamboo-init.properties"
      state: present
      regexp: '^bamboo.home'
      line: "bamboo.home=/opt/{{bamboo5_directory}}"

  - name: install bamboo service
    template:
      src: bamboo5
      dest: /etc/init.d/bamboo
      owner: root
      group: root
      mode: 0755

  - name: start bamboo service
    service:
      name: bamboo
      enabled: yes
      state: restarted