---
  - include_vars: "{{playbook_dir}}/vars/encrypted.yml"

  - name: Download AWS Client
    win_get_url:
      url: "https://s3.amazonaws.com/bamboo-support/AWSCLI64.msi"
      dest: C:\Apps\AWSCLI64.msi

  - name: Install AWS Client
    win_msi:
      path: C:\Apps\AWSCLI64.msi
      wait: true

  - name: Download SQL Server Express 2016
    win_get_url:
      url: "https://s3.amazonaws.com/bamboo-support/SQLEXPR_x64_ENU.exe"
      dest: C:\Apps\SQLEXPR_x64_ENU.exe

  - name: Extract SQL Server Express
    win_command: C:\Apps\SQLEXPR_x64_ENU.exe SQLEXPR_x64_ENU.exe /q /x:C:\Apps\SqlServerExpress
    args:
      creates: C:\Apps\SqlServerExpress

  - name: Copy SQL Server Install Script
    win_template:
      src: SQLInstall.ps1
      dest: C:\Apps\SQLInstall.ps1

  # You can find logs of the attempted installs at
  # C:\Program Files\Microsoft SQL Server\130\Setup Bootstrap\Log
  - name: Install SQL Express
    win_shell: C:\Apps\SQLInstall.ps1
    args:
      creates: C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS

  - name: Install Octopus CLI Tools
    win_chocolatey:
      name: octopustools
      state: present
      version: "{{octopus_tools_version}}"
    register: choco_octopuscli
    until: choco_octopuscli.rc == 0
    retries: 5
    delay: 10

  - name: Debug Chocolatey Output
    debug:
        msg: "{{choco_octopuscli}}"

  - name: Install Octopus Deploy
    win_chocolatey:
      name: octopusdeploy
      state: present
      version: "{{octopus_version}}"
    register: choco_octopusserver
    until: choco_octopusserver.rc == 0
    retries: 5
    delay: 10

  - name: Install Octopus Deploy Tentacle
    win_chocolatey:
      name: octopusdeploy.tentacle
      state: present
      version: "{{octopus_version}}"
    register: choco_tentacle
    until: choco_tentacle.rc == 0
    retries: 5
    delay: 10

  - name: Copy Octopus Server Creation Script
    win_template:
      src: OctopusDeploy.ps1
      dest: C:\Apps\OctopusDeploy.ps1

  - name: Install Octopus Deploy Server
    win_shell: C:\Apps\OctopusDeploy.ps1
    args:
      creates: C:\Octopus
    register: deploy_server

  - name: Copy Octopus API Key Create Script
    win_template:
      src: ApiKey.ps1
      dest: C:\Apps\ApiKey.ps1

  - name: Create API key
    win_shell: C:\Apps\ApiKey.ps1
    register: api_key

  - name: Copy Octopus Environment Create Script
    win_template:
      src: OctopusEnvironment.ps1
      dest: C:\Apps\OctopusEnvironment.ps1

  - name: Create Environment
    win_shell: C:\Apps\OctopusEnvironment.ps1
    register: create_environment

  - name: Copy Octopus Tentacle Install Script
    win_template:
      src: OctopusTentacle.ps1
      dest: C:\Apps\OctopusTentacle.ps1

  - name: Install Tentacle
    win_shell: C:\Apps\OctopusTentacle.ps1
    args:
      creates: C:\Octopus\Applications
    register: create_tentacle

  - name: Open Firewall For Server
    win_shell: netsh advfirewall firewall add rule name="Octopus Deploy" dir=in action=allow protocol=TCP localport=80 profile=public

  - name: Open Firewall For Tentacle
    win_shell: netsh advfirewall firewall add rule name="Octopus Deploy" dir=in action=allow protocol=TCP localport=10933 profile=public

  - name: Copy Octopus SSH Account Install Script
    win_template:
      src: ImportDukeLegionCertificate.ps1
      dest: C:\Apps\ImportDukeLegionCertificate.ps1

  - name: Install SSH Account
    win_shell: C:\Apps\ImportDukeLegionCertificate.ps1

  - name: Copy Query Script
    win_template:
      src: QueryAndRegisterSSH.ps1
      dest: C:\Apps\QueryAndRegisterSSH.ps1

  - name: Copy Register Script
    win_template:
      src: RegisterSSH.ps1
      dest: C:\Apps\RegisterSSH.ps1

  - name: Copy Package Upload Script
    win_template:
      src: OctopusPackagePush.ps1
      dest: C:\Apps\OctopusPackagePush.ps1

  - name: Copy Packages
    win_copy:
      src: group_files/package/demo.0.0.1.zip
      dest: C:\Apps\demo.0.0.1.zip

  - name: Copy Packages
    win_copy:
      src: group_files/package/samplewebapp.1.0.0.0.nupkg
      dest: C:\Apps\samplewebapp.1.0.0.0.nupkg

  - name: Install Packages
    win_shell: C:\Apps\OctopusPackagePush.ps1
