---
  - include_vars: encrypted.yml
  - include_vars: main.yml

#  - name: Disable UAC
#    win_shell: New-ItemProperty -Path HKLM:Software\Microsoft\Windows\CurrentVersion\policies\system -Name EnableLUA -PropertyType DWord -Value 0 -Force

#  - name: Reboot Server
#    win_reboot:
#      shutdown_timeout_sec: 3600
#      reboot_timeout_sec: 3600

#  - name: Install DotNET
#    win_feature:
#      name: NET-Framework-Core,NET-Framework-Features,NET-Framework-45-Features,NET-Framework-45-Core,NET-Framework-45-ASPNET
#      state: present

  # This is to get around permission issues that cause
  # "There was an error generating the XML document" errors
  # when installing SQL Server
#  - name: Create admin user to install SQL Express
#    win_user:
#      name: "{{sql_install_user}}"
#      password: "{{sql_install_user_password}}"
#      state: present
#      groups:
#        - Administrators

  - name: Download SQL Server Express 2016
    win_get_url:
      url: "https://s3.amazonaws.com/bamboo-support/SQLEXPR_x64_ENU.exe"
      dest: C:\Apps\SQLEXPR_x64_ENU.exe

  - name: Extract SQL Server Express
    win_command: C:\Apps\SQLEXPR_x64_ENU.exe SQLEXPR_x64_ENU.exe /q /x:C:\Apps\SqlServerExpress
    args:
      creates: C:\Apps\SqlServerExpress

  - name: Copy SQL Server Install Script
    win_template:
      src: SQLInstall.ps1
      dest: C:\Apps\SQLInstall.ps1

  # You can find logs of the attempted installs at
  # C:\Program Files\Microsoft SQL Server\130\Setup Bootstrap\Log
  - name: Install SQL Express
    win_shell: C:\Apps\SQLInstall.ps1
    args:
      creates: C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS

  - name: Install Octopus CLI Tools
    win_chocolatey:
      name: octopustools
      state: present

  - name: Install Octopus Deploy
    win_chocolatey:
      name: octopusdeploy
      state: present

  - name: Install Octopus Deploy Tentacle
    win_chocolatey:
      name: octopusdeploy.tentacle
      state: present

  - name: Copy Octopus Server Creation Script
    win_template:
      src: OctopusDeploy.ps1
      dest: C:\Apps\OctopusDeploy.ps1

  - name: Install Octopus Deploy Server
    win_shell: C:\Apps\OctopusDeploy.ps1
    args:
      creates: C:\Octopus
    register: deploy_server

  - name: Copy Octopus API Key Create Script
    win_template:
      src: ApiKey.ps1
      dest: C:\Apps\ApiKey.ps1

  - name: Create API key
    win_shell: C:\Apps\ApiKey.ps1
    register: api_key

  - name: Copy Octopus Environment Create Script
    win_template:
      src: OctopusEnvironment.ps1
      dest: C:\Apps\OctopusEnvironment.ps1

  - name: Create Environment
    win_shell: C:\Apps\OctopusEnvironment.ps1
    register: create_environment

  - name: Copy Octopus Tentacle Install Script
    win_template:
      src: OctopusTentacle.ps1
      dest: C:\Apps\OctopusTentacle.ps1

  - name: Install Tentacle
    win_shell: C:\Apps\OctopusTentacle.ps1
    args:
      creates: C:\Octopus\Applications
    register: create_tentacle