---
- name: Terminate the EC2 instance
  ec2:
    state: absent
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    security_token: "{{ security_token }}"
    instance_ids: "{{ instance_id }}"
    region: "{{ region }}"