---
sql_instance_name: SQLEXPRESS
sql_install_user: sqlexpress_install
# Leave this blank, and override from the command line if required
octopus_version: "latest"
octopus_tools_version: "latest"
octopus_tentacle_version: "latest"