---
  - include_vars: encrypted.yml

  - name: "Create WildFly User {{wildfly_role}}"
    user:
      name: "{{wildfly_role}}"

  - name: "Stop Existing Service {{wildfly_role}}"
    service:
      name: "{{wildfly_role}}"
      enabled: yes
      state: stopped
    ignore_errors: yes

  - name: "Kill Existing Processes {{wildfly_role}}"
    command: "pkill -9 -U {{wildfly_role}}"
    ignore_errors: yes

  - name: "Download Wildfly Distribution {{wildfly_role}}"
    get_url:
        url: "{{wildfly_download}}"
        dest: "/tmp/{{wildfly_role}}.tar.gz"
        mode: 0440

  - name: "Creates directory {{wildfly_role}}"
    file:
      path: "/opt/{{wildfly_role}}"
      state: directory

  - name: "Extract WildFly {{wildfly_role}}"
    unarchive:
        src: "/tmp/{{wildfly_role}}.tar.gz"
        dest: "/opt/{{wildfly_role}}"
        copy: no

  - name: "Set WildFly Directory Permissions {{wildfly_role}}"
    file:
      state: directory
      path: "/opt/{{wildfly_role}}"
      owner: "{{wildfly_role}}"
      group: "{{wildfly_role}}"
      recurse: true

  - name: "Create Logging Directory {{wildfly_role}}"
    file:
      state: directory
      path: "{{wildfly_logging_dir}}"
      owner: "{{wildfly_role}}"
      group: "{{wildfly_role}}"
      recurse: true

  - name: "Add Management Users {{wildfly_role}}"
    command: "{{wildfly_install_dir}}/bin/add-user.sh {{wildfly_admin_user}} {{wildfly_admin_password}}"

  - name: "Add Slave Users {{wildfly_role}}"
    command: "{{wildfly_install_dir}}/bin/add-user.sh {{wildfly_slave_username}} {{wildfly_slave_password}}"

  - name: "Add Redhat Wildfly Service {{wildfly_role}}"
    template:
      src: wildfly-init-redhat.sh
      dest: "/etc/init.d/{{wildfly_role}}"
      owner: root
      group: root
      mode: 0755
    when: '"centos_server" in group_names'

  - name: "Add Debian Wildfly Service {{wildfly_role}}"
    template:
      src: wildfly-init-debian.sh
      dest: "/etc/init.d/{{wildfly_role}}"
      owner: root
      group: root
      mode: 0755
    when: '"ubuntu_server" in group_names'

  - name: "Copy vault keystore {{wildfly_role}}"
    copy:
      src: group_files/wildfly/vault.keystore
      dest: "{{wildfly_install_dir}}/vault.keystore"
      owner: "{{wildfly_role}}"
      group: "{{wildfly_role}}"
      mode: 0644

  - name: "Add passwords to vault {{wildfly_role}}"
    command: "{{wildfly_install_dir}}/bin/vault.sh -k {{wildfly_install_dir}}/vault.keystore -p {{vault_password}} -e {{wildfly_install_dir}}/vault -i 50 -s {{salt}} -v vault -b MyVault -a {{item.name}} -x {{item.password}}"
    with_items: "{{passwords}}"
    no_log: true

  - name: "Copy Slave Configuration {{wildfly_role}}"
    template:
      src: "{{playbook_dir}}/templates/{{wildfly_template_dir}}/host-slave.xml"
      dest: "{{wildfly_install_dir}}/domain/configuration/host-slave.xml"
      owner: "{{wildfly_role}}"
      group: "{{wildfly_role}}"

  - name: "Copy Slave local Configuration {{wildfly_role}}"
    template:
      src: "{{playbook_dir}}/templates/{{wildfly_template_dir}}/host-slave-local.xml"
      dest: "{{wildfly_install_dir}}/domain/configuration/host-slave-local.xml"
      owner: "{{wildfly_role}}"
      group: "{{wildfly_role}}"

  - name: "Copy DC Domain Configuration {{wildfly_role}}"
    template:
      src: "{{playbook_dir}}/templates/{{wildfly_template_dir}}/domain.xml"
      dest: "{{wildfly_install_dir}}/domain/configuration/domain.xml"
      owner: "{{wildfly_role}}"
      group: "{{wildfly_role}}"

  - name: "Copy DC Host Configuration {{wildfly_role}}"
    template:
      src: "{{playbook_dir}}/templates/{{wildfly_template_dir}}/host-master.xml"
      dest: "{{wildfly_install_dir}}/domain/configuration/host-master.xml"
      owner: "{{wildfly_role}}"
      group: "{{wildfly_role}}"

  - name: "Copy DC Host Local Configuration {{wildfly_role}}"
    template:
      src: "{{playbook_dir}}/templates/{{wildfly_template_dir}}/host-master-local.xml"
      dest: "{{wildfly_install_dir}}/domain/configuration/host-master-local.xml"
      owner: "{{wildfly_role}}"
      group: "{{wildfly_role}}"

  - name: "Allow SSH user to add files to config dir"
    file:
      state: directory
      path: "{{wildfly_install_dir}}/domain/configuration"
      owner: "{{wildfly_role}}"
      group: "{{wildfly_role}}"
      mode: "0777"

  - name: "New files should belong to the wildfly user, and protected from deletion"
    file:
      state: directory
      path: "{{wildfly_install_dir}}/domain/configuration"
      owner: "{{wildfly_role}}"
      group: "{{wildfly_role}}"
      mode: "o+t,u+s,g+s"

  - name: "Allow SSH user to add files to config dir"
    file:
      state: directory
      path: "{{wildfly_install_dir}}/standalone/configuration"
      owner: "{{wildfly_role}}"
      group: "{{wildfly_role}}"
      mode: "0777"

  - name: "New files should belong to the wildfly group, and protected from deletion"
    file:
      state: directory
      path: "{{wildfly_install_dir}}/standalone/configuration"
      mode: "o+t,g+s"