---

  - name: Create Windows Server
    ec2:
      key_name: OctopusVirginia
      instance_type: m3.medium
      image: "{{win_ami}}"
      wait: yes
      wait_timeout: 600
      group: OctopusHttp
      count: 1
      region: us-east-1
      user_data: "{{ lookup('template', 'template/userdata.txt.j2') }}"
      instance_tags:
        Appplication: OctopusDeploy
        Domain: None
        Environment: Test
        LifeTime: Permanent
        Name: Octopus Deploy
        OwnerContact: "@matthew.casperson"
        Source: Ansible
    register: windows_server_ec2

  - name: Get the Administrator password
    ec2_win_password:
      instance_id: "{{windows_server_ec2.instances[0].id}}"
      region: us-east-1
      key_file: "/mnt/c/Users/matth/Downloads/OctopusVirginia.pem"
      wait: true
      wait_timeout: 600
    register: windows_password

  - name: Add Host to Inventory
    add_host:
      name: "{{ windows_server_ec2.instances[0].public_ip }}"
      groups: created_nodes
      ansible_user: Administrator
      ansible_port: 5986
      ansible_password: "{{windows_password}}"
      ansible_connection: winrm
      ansible_winrm_server_cert_validation: ignore

  - name: Wait for WinRM to answer on all hosts
    wait_for:
      port: 5986
      host: "{{ windows_server_ec2.instances[0].public_ip }}"
      timeout: 600

