---

  - name: Create Linux Server
    ec2:
      key_name: "{{key_name}}"
      instance_type: "{{instance_type}}"
      image: "{{centos_ami}}"
      wait: yes
      group: "{{security_group}}"
      count: 1
      region: "{{region}}"
      wait_timeout: 3000
      volumes:
        - device_name: /dev/sda1
          volume_size: 80
          volume_type: gp2
          delete_on_termination: true
      instance_tags:
        Appplication: "{{application_tag}}"
        Domain: None
        Environment: "{{environment_tag}}"
        LifeTime: "{{lifetime_tag}}"
        Name: "{{name_tag}}"
        OwnerContact: "@matthew.casperson"
        Source: Ansible
    register: linux_server_ec2

  - name: Add Host to Inventory
    add_host:
      name: "{{ item.public_ip }}"
      groups:
        - centos_server
        - linux_server
        - "{{location}}_server"
    with_items: "{{linux_server_ec2.instances}}"

  - name: Wait for SSH to answer on all hosts
    wait_for:
      port: 22
      host: "{{ item.public_ip }}"
      timeout: 600
    with_items: "{{linux_server_ec2.instances}}"

  - name: Pause for a bit
    pause:
      seconds: 30