---
- name: Linux Server
  hosts:
    - 127.0.0.1
  become: false
  gather_facts: false

  roles:
    - centos-7-server-instance

  vars:
    centos_ami: "ami-ae7bfdb8"
    location: "virgina"
    vpc_subnet:
    assign_public_ip:
    key_name: "DukeLegion"
    instance_type: "m3.2xlarge"
    security_group: "WildFlyTomcat"
    region: "us-east-1"
    ec2_role:
    domain_tag: "None"
    application_tag: "Centos WildFly Tomcat"
    name_tag: "Centos WildFly Tomcat"
    environment_tag: "Test"
    lifetime_tag: "Permanent"
    owner_tag: "@matthew.casperson"
    "scheduler:ec2-startstop": "true"

- name: linux instance prep
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - yum-linux-common
    
- name: wildfly 10 dc
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-wildfly10-dc-local

- name: wildfly 10 slave
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-wildfly10-slave-local

- name: eap 6 dc
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-eap6-dc-local

- name: eap 6 slave
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-eap6-slave-local

- name: eap 7 dc
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-eap7-dc-local

- name: eap 7 slave
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-eap7-slave-local    

- name: payara 4
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-payara4

- name: liberty 7
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-liberty7

- name: wildfly standalone 10
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-wildfly10-standalone

- name: EAP 6 Standalone
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-eap6-standalone

- name: EAP 7 Standalone
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-eap7-standalone

- name: Tomcat 7
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-tomcat7

- name: Tomcat 8
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-tomcat8

- name: Tomcat 9
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-tomcat9

- name: wildfly standalone
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-wildfly11-dc-local

- name: wildfly standalone
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-wildfly11-slave-local

- name: wildfly standalone
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-wildfly11-standalone