---
- name: Linux Server
  hosts:
    - 127.0.0.1
  become: false
  gather_facts: false

  roles:
    - centos-7-server-instance

  vars:
    centos_ami: "ami-ae7bfdb8"
    location: "virgina"
    vpc_subnet:
    assign_public_ip:
    key_name: "DukeLegion"
    instance_type: "m3.xlarge"
    security_group: "WildFlyTomcat"
    region: "us-east-1"
    ec2_role:
    domain_tag: "None"
    application_tag: "Centos WildFly Tomcat"
    name_tag: "Centos WildFly Tomcat"
    environment_tag: "Test"
    lifetime_tag: "Permanent"
    owner_tag: "@matthew.casperson"

- name: linux instance prep
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - yum-linux-common

- name: Tomcat 7
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-tomcat7

- name: Tomcat 8
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-tomcat8

- name: Tomcat 9
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-tomcat9

- name: EAP 6 Standalone
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-eap6-standalone

- name: EAP 7 Standalone
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-eap7-standalone

- name: wildfly standalone
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-wildfly11-dc-local

- name: wildfly standalone
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-wildfly11-slave-local

- name: wildfly standalone
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-wildfly11-standalone

- name: Tomcat
  hosts: centos_server
  remote_user: centos
  become: true
  become_user: root

  roles:
    - linux-tomcat