---
- name: Linux Server
  hosts:
    - 127.0.0.1
  become: false
  gather_facts: false

  roles:
    - ubuntu-1704-server-instance

  vars:
      location: "virgina"
      key_name: "OctopusVirgina"
      instance_type: "m3.xlarge"
      security_group: "WildFlyTomcat"
      region: "us-east-1"
      application_tag: "Ubuntu WildFly Tomcat"
      name_tag: "Ubuntu WildFly Tomcat"
      environment_tag: "Test"
      lifetime_tag: "Permanent"

- name: linux instance prep
  hosts: ubuntu_server
  remote_user: ubuntu
  become: true
  become_user: root

  roles:
    - apt-linux-common

- name: wildfly standalone
  hosts: ubuntu_server
  remote_user: ubuntu
  become: true
  become_user: root

  roles:
    - linux-wildfly-dc-local

- name: wildfly standalone
  hosts: ubuntu_server
  remote_user: ubuntu
  become: true
  become_user: root

  roles:
    - linux-wildfly-slave-local

- name: wildfly standalone
  hosts: ubuntu_server
  remote_user: ubuntu
  become: true
  become_user: root

  roles:
    - linux-wildfly-standalone

- name: Tomcat
  hosts: ubuntu_server
  remote_user: ubuntu
  become: true
  become_user: root

  roles:
    - linux-tomcat