---
- name: Linux Server
  hosts:
    - 127.0.0.1
  become: false
  gather_facts: false

  roles:
    - ubuntu-1704-server-instance

- name: linux instance prep
  hosts: linux_server
  remote_user: ubuntu
  become: true
  become_user: root

  roles:
    - apt-linux-common