---
# This playbook creates a Windows Server instance in AWS and installs:
# Octopus Deploy
# WildFly Standalone
# Wildfly Domain Controller and Slave
- name: Octopus Deploy Windows Server
  hosts:
    - 127.0.0.1
  become: false
  gather_facts: false

  roles:
    - win-server-instance

  vars:
    region: "us-east-1"

- name: Windows Instance Prep
  hosts: windows_server
  become: false
  gather_facts: false

  roles:
    - win-common

- name: Octopus Deploy
  hosts: windows_server
  become: false

  roles:
    - win-octopus-deploy
    - win-e2e-tests

- name: payara 4
  hosts: windows_server
  become: false

  roles:
    - win-payara4

- name: liberty 7
  hosts: windows_server
  become: false

  roles:
    - win-liberty7

- name: wildfly standalone
  hosts: windows_server
  become: false

  roles:
    - win-wildfly11-dc-local

- name: wildfly standalone
  hosts: windows_server
  become: false

  roles:
    - win-wildfly11-slave-local

- name: wildfly standalone
  hosts: windows_server
  become: false

  roles:
    - win-wildfly11-standalone

- name: Wildfly 10 Standalone
  hosts: windows_server
  become: false

  roles:
    - win-wildfly10-standalone

- name: EAP 6 Standalone
  hosts: windows_server
  become: false

  roles:
    - win-eap6-standalone

- name: Tomcat 7
  hosts: windows_server
  become: false

  roles:
    - win-tomcat7

- name: Tomcat 8
  hosts: windows_server
  become: false

  roles:
    - win-tomcat8

- name: Tomcat 9
  hosts: windows_server
  become: false

  roles:
    - win-tomcat9
