---
# This playbook creates a Windows Server instance in AWS and installs:
# Octopus Deploy
# WildFly Standalone
# Wildfly Domain Controller and Slave
- name: Octopus Deploy Windows Server
  hosts:
    - 127.0.0.1
  become: false
  gather_facts: false

  roles:
    - win-server-instance

  vars:
    region: "us-east-1"

- name: Windows Instance Prep
  hosts: windows_server
  become: false
  gather_facts: false

  roles:
    - win-common

- name: Octopus Deploy
  hosts: windows_server
  become: false

  roles:
    - win-octopus-deploy
    - win-e2e-tests

- name: wildfly standalone
  hosts: windows_server
  become: false

  roles:
    - win-wildfly-dc-local

- name: wildfly standalone
  hosts: windows_server
  become: false

  roles:
    - win-wildfly-slave-local

- name: wildfly standalone
  hosts: windows_server
  become: false

  roles:
    - win-wildfly-standalone

- name: Tomcat
  hosts: windows_server
  become: false

  roles:
    - win-tomcat
