---
# This playbook creates a Windows Server instance in AWS and installs:
# Octopus Deploy
# WildFly Standalone
# Wildfly Domain Controller and Slave
- name: Octopus Deploy Windows Server
  hosts:
    - 127.0.0.1
  become: false
  gather_facts: false

  roles:
    - win-server-instance

  vars:
    region: "us-east-1"

- name: Windows Instance Prep
  hosts: windows_server
  become: false
  gather_facts: false

  roles:
    - win-common
    - win-octopus-deploy
    - win-e2e-tests
    - win-wildfly-dc-local
    - win-wildfly-standalone
    - win-tomcat
