---
  - name: Create download directory
    win_file:
      path: C:\Apps
      state: directory

  - name: Download Java
    win_get_url:
      url: "https://s3.amazonaws.com/bamboo-support/jdk-8u131-windows-x64.exe"
      dest: C:\Apps\jdk-8u131-windows-x64.exe

  - name: Install Java
    win_command: C:\Apps\jdk-8u131-windows-x64.exe /s ADDLOCAL="ToolsFeature,SourceFeature,PublicjreFeature" INSTALLDIR=C:\Java\x86\jdk1.8.0_131 /INSTALLDIRPUBJRE=C:\Java\x86\jre1.8.0_131

  - name: Download Groovy
    win_get_url:
      url: "https://s3.amazonaws.com/bamboo-support/groovy-2.4.11-installer.exe"
      dest: C:\Apps\groovy-2.4.11-installer.exe

  - name: Install Groovy
    win_command: C:\Apps\groovy-2.4.11-installer.exe /S /A /N /D=C:\groovy

  - name: Ensure Groovy is on the path
    win_path:
      elements:
      - 'C:\groovy\bin'

  - name: Download OpenSSL
    win_get_url:
      url: "https://s3.amazonaws.com/bamboo-support/Win64OpenSSL-1_0_2L.exe"
      dest: C:\Apps\Win64OpenSSL-1_0_2L.exe

  - name: Install OpenSSL
    win_command: C:\Apps\Win64OpenSSL-1_0_2L.exe /silent /verysilent /sp- /suppressmsgboxes

  - name: Ensure OpenSSL is on the path
    win_path:
      elements:
      - 'C:\OpenSSL-Win64\bin'

  - name: Download Git
    win_get_url:
      url: "https://s3.amazonaws.com/bamboo-support/Git-2.13.1.2-64-bit.exe"
      dest: C:\Apps\Git-2.13.1.2-64-bit.exe

  - name: Install Git
    win_command: C:\Apps\Git-2.13.1.2-64-bit.exe /SILENT /COMPONENTS="icons,ext\reg\shellhere,assoc,assoc_sh"

  - name: Download Chrome
    win_get_url:
      url: "https://s3.amazonaws.com/bamboo-support/ChromeStandaloneSetup64.exe"
      dest: C:\Apps\ChromeStandaloneSetup64.exe

  - name: Install Chrome
    win_command: C:\Apps\ChromeStandaloneSetup64.exe /silent /install

  - name: Download Notepad++
    win_get_url:
      url: "https://s3.amazonaws.com/bamboo-support/npp.7.5.1.Installer.x64.exe"
      dest: C:\Apps\npp.7.5.1.Installer.x64.exe

  - name: Install Notepad++
    win_command: C:\Apps\npp.7.5.1.Installer.x64.exe /S

  - name: Download JCE
    win_get_url:
      url: https://s3.amazonaws.com/bamboo-support/jce_policy-8.zip
      dest: C:\Apps\jce_policy-8.zip

  - name: Unzip JCE
    win_unzip:
      src: C:\Apps\jce_policy-8.zip
      dest: C:\Apps

  - name: Install JCE
    win_shell: "&xcopy C:\\Apps\\UnlimitedJCEPolicyJDK8 \"C:\\Java\\x86\\jre1.8.0_131\\lib\\security\" /E /Y"


  - name: Download 7zip
    win_get_url:
      url: "https://s3.amazonaws.com/bamboo-support/7z1604-x64.exe"
      dest: C:\Apps\7z1604-x64.exe

  - name: Install 7zip
    win_command: C:\Apps\7z1604-x64.exe /S /D=C:\7Zip

  - name: Install IIS Web-Server with sub features and management tools
    win_feature:
      name: Web-Server
      state: present
      restart: True
      include_sub_features: True
      include_management_tools: True

#  - name: Download SDK
#    win_get_url:
#      url: "https://sdkrepo.atlassian.com/win-signed/sdk-installer-6.2.14.exe"
#      dest: C:\Apps\sdk-installer-6.2.14.exe

#  - name: Install SDK
#    win_command: C:\Apps\sdk-installer-6.2.14.exe -q -overwrite
