---
  - name: Install Java
    win_chocolatey:
      name: jdk8
      state: present
      timeout: 10000
    register: java_result
    retries: 5
    delay: 10
    until: java_result | success

  - name: Install Groovy
    win_chocolatey:
      name: groovy
      state: present
      timeout: 10000
    register: groovy_result
    retries: 5
    delay: 10
    until: groovy_result | success

  - name: Download Chrome
    win_get_url:
      url: https://s3.amazonaws.com/bamboo-support/ChromeStandaloneSetup64.exe
      dest: C:\Apps\ChromeStandaloneSetup64.exe

  - name: Install Chrome
    win_command: C:\Apps\ChromeStandaloneSetup64.exe /silent /install

#  - name: Install Chrome
#    win_chocolatey:
#      name: googlechrome
#      state: present
#      timeout: 10000
#    register: chrome_result
#    retries: 5
#    delay: 10
#    until: chrome_result | success

#  - name: Install Sysinternals
#    win_chocolatey:
#      name: sysinternals
#      state: present

  - name: Install Notepad ++
    win_chocolatey:
      name: notepadplusplus.install
      state: present

  - name: Create download directory
    win_file:
      path: C:\Apps
      state: directory

  - name: Download JCE
    win_get_url:
      url: https://s3.amazonaws.com/bamboo-support/jce_policy-8.zip
      dest: C:\Apps\jce_policy-8.zip

  - name: Unzip JCE
    win_unzip:
      src: C:\Apps\jce_policy-8.zip
      dest: C:\Apps

  - name: Install JCE
    win_shell: "&xcopy C:\\Apps\\UnlimitedJCEPolicyJDK8 \"C:\\Program Files\\Java\\jdk1.8.0_131\\jre\\lib\\security\" /E /Y"

#  - name: Download SDK
#    win_get_url:
#      url: "https://sdkrepo.atlassian.com/win-signed/sdk-installer-6.2.14.exe"
#      dest: C:\Apps\sdk-installer-6.2.14.exe

#  - name: Install SDK
#    win_command: C:\Apps\sdk-installer-6.2.14.exe -q -overwrite
