---

  - name: Install Java
    win_chocolatey:
      name: jdk8
      state: present

  - name: Install Groovy
    win_chocolatey:
      name: groovy
      state: present

  - name: Install Chrome
    win_chocolatey:
      name: googlechrome
      state: present

  - name: Create download directory
    win_file:
      path: C:\Apps
      state: directory

  - name: Download SDK
    win_get_url:
      url: "https://sdkrepo.atlassian.com/win-signed/sdk-installer-6.2.14.exe"
      dest: C:\Apps\sdk-installer-6.2.14.exe

  - name: Install SDK
    win_command: C:\Apps\sdk-installer-6.2.14.exe -q -overwrite
