---
  - name: Add EPEL repository
    yum:
      name: https://s3.amazonaws.com/bamboo-support/epel-release-7-9.noarch.rpm
      state: present

  - name: install useful packages
    yum:
      name: wget,elinks,telnet,htop,mlocate,python-pip,vim,nano,jq,java-1.8.0-openjdk-devel,unzip,maven,libunwind,libicu,git,patch,zip,net-tools,openssl-devel,expat-devel

  - name: install packagers for docker
    yum:
      name: yum-utils,device-mapper-persistent-data,lvm2

  - name: install development tools
    yum:
      name: "@Development Tools"

  - name: install mono key
    get_url:
        url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        dest: /tmp/GPG-KEY-mono
        mode: 0440

  - name: import mono key
    rpm_key:
      state: present
      key: /tmp/GPG-KEY-mono

  - name: Add mono repo
    yum_repository:
      name: mono
      description: Mono repository
      baseurl: http://download.mono-project.com/repo/centos7/
      gpgkey: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
      gpgcheck: yes
      enabled: yes

  - name: install mono
    yum:
      name: mono-devel

  - name: Install Docker repo
    template:
      src: "docker-ce.repo"
      dest: "/etc/yum.repos.d/docker-ce.repo"
      owner: "root"
      group: "root"
      mode: 0644

  - name: install docker
    yum:
      name: docker-ce

  - name: Start Docker
    service:
      name: docker
      enabled: yes
      state: started

  - name: Set JAVA_HOME
    lineinfile: dest=/etc/environment state=present regexp='^JAVA_HOME' line='JAVA_HOME=/usr/lib/jvm/jre-1.8.0'

  - name: Copy APR compilation script to /opt
    template:
      src: "aprbuild.sh"
      dest: "/opt/aprbuild.sh"
      owner: "root"
      group: "root"
      mode: 0774

  - name: Build APR
    command: "/opt/aprbuild.sh"
