---
wildfly_user: wildfly
wildfly_download: https://s3.amazonaws.com/bamboo-support/wildfly-11.0.0.Alpha1.tar.gz
wildfly_versioned_dir: wildfly-11.0.0.Alpha1
wildfly_install_dir: /opt/wildfly
wildfly_logging_dir: /var/log/wildfly
wildfly_admin_user: admin
wildfly_slave_username: slave