---

  - name: Install Domain Controller Service
    win_command: "{{wildfly_install_dir}}\\bin\\service\\service.bat install /jbossuser {{wildfly_admin_user}} /jbosspass {{wildfly_admin_password}} /controller {{ansible_ip_addresses[0]}}:19990 /startup /name \"{{wildfly_domain_controller_service}}\" /host /hostconfig host-master-local.xml"

  - name: Start Domain Controller Service
    win_service:
      name: "{{wildfly_domain_controller_service}}"
      state: started
    ignore_errors: yes

  - name: Open Firewall For Admin
    win_shell: "netsh advfirewall firewall add rule name=\"Wildfly 10\" dir=in action=allow protocol=TCP localport={{wildfly_domaincontroller_management_http_port}} profile=public"


  - name: Add WildFly Shortcut
    win_shortcut:
      src: '%PROGRAMFILES(x86)%\Google\Chrome\Application\chrome.exe'
      dest: '%PUBLIC%\Desktop\WildFly 11 Domain Admin.lnk'
      args: "--new-window http://localhost:{{wildfly_domaincontroller_management_http_port}}/"
      directory: '%PROGRAMFILES(x86)%\Google\Chrome\Application'
      icon: '%PROGRAMFILES(x86)%\Google\Chrome\Application\chrome.exe,0'