---
  - name: Copy Modified Configuration
    template:
      src: "{{playbook_dir}}/templates/wildfly/host-slave-11-0-0-Alpha1.xml"
      dest: "{{wildfly_install_dir}}/domain/configuration/host-slave.xml"

  - name: Install Slave Service
    win_command: "{{wildfly_install_dir}}\\bin\\service\\service.bat install /startup /name \"{{wildfly_slave_service}}\" /host /hostconfig host-slave.xml"

  - name: Start Slave Service
    win_service:
      name: "{{wildfly_slave_service}}"
      state: started
    ignore_errors: yes