---
  - name: Install Slave Service
    win_command: "{{wildfly_install_dir}}\\bin\\service\\service.bat install /jbossuser {{wildfly_admin_user}} /jbosspass {{wildfly_admin_password}} /controller localhost:{{wildfly_domaincontroller_management_native_port}} /startup /name \"{{wildfly_domain_controller_service}} /host /hostconfig host-master-local.xml\""

  - name: Start Standalone Service
    win_service:
      name: "{{wildfly_domain_controller_service}}"
      state: started
    ignore_errors: yes

  - name: Add WildFly Shortcut
    win_shortcut:
      src: '%PROGRAMFILES(x86)%\Google\Chrome\Application\chrome.exe'
      dest: '%PUBLIC%\Desktop\EAP 6 DC Local Admin.lnk'
      args: '--new-window http://{{ansible_ip_addresses[0]}}:{{wildfly_domaincontroller_management_http_port}}/'
      directory: '%PROGRAMFILES(x86)%\Google\Chrome\Application'
      icon: '%PROGRAMFILES(x86)%\Google\Chrome\Application\chrome.exe,0'
