---
  - name: Download Iridium
    win_get_url:
      url: https://s3.amazonaws.com/iridium-release/IridiumApplicationTesting.jar
      dest: C:\Apps\IridiumApplicationTesting.jar

  - name: Download Atom Text Editor
    win_get_url:
      url: https://s3.amazonaws.com/bamboo-support/AtomSetup-x64.exe
      dest: C:\Apps\AtomSetup-x64.exe

  - name: Install Atom Text Editor
    win_command: C:\Apps\AtomSetup-x64.exe --silent

  - name: Create Tests Directory
    win_file:
      path: C:\E2ETests
      state: directory

  - name: Create Tests Library Directory
    win_file:
      path: C:\E2ETests\lib
      state: directory

  - name: Copy Test Scripts
    template:
      src: "{{item}}"
      dest: "C:\\E2ETests\\{{ item | regex_replace(role_path + '/templates','') | regex_replace('/', '\\\\') }}"
    with_items: "{{ lookup('pipe','find {{role_path}}/templates -type f').split('\n') }}"

  - name: Run simple end to end test
    win_shell: C:\E2ETests\hello-world-project.ps1
