---
  - name: Install SQL Server Express
    win_chocolatey:
      name: mssqlserver2014express
      state: present

  - name: Install Octopus CLI Tools
    win_chocolatey:
      name: octopustools
      state: present

  - name: Install Octopus Deploy
    win_chocolatey:
      name: octopusdeploy
      state: present

  - name: Install Octopus Deploy Tentacle
    win_chocolatey:
      name: octopusdeploy.tentacle
      state: present