---
  - include_vars: encrypted.yml

  - name: Download SQL Server Express 2016
    win_get_url:
      url: "https://s3.amazonaws.com/bamboo-support/SQLEXPR_x64_ENU.exe"
      dest: C:\Apps\SQLEXPR_x64_ENU.exe

  - name: Copy SQL Install Script
    win_template:
      src: sqlexpress2016.ini
      dest: C:\Apps\sqlexpress2016.ini

  - name: Extract SQL Server Express
    win_command: C:\Apps\SQLEXPR_x64_ENU.exe SQLEXPR_x64_ENU.exe /q /x:C:\Apps\SqlServerExpress

  - name: Install SQL Server Express
    win_command: C:\Apps\SQLEXPR_x64_ENU.exe /Q /ACTION=INSTALL /IACCEPTSQLSERVERLICENSETERMS /ConfigurationFile="C:\Apps\sqlexpress2016.ini"

  - name: Install Octopus CLI Tools
    win_chocolatey:
      name: octopustools
      state: present

  - name: Install Octopus Deploy
    win_chocolatey:
      name: octopusdeploy
      state: present

  - name: Install Octopus Deploy Tentacle
    win_chocolatey:
      name: octopusdeploy.tentacle
      state: present

  - name: Copy Octopus Server Creation Script
    win_template:
      src: OctopusDeploy.ps1
      dest: C:\Apps\OctopusDeploy.ps1

  - name: Install Octospus Deploy Server
    win_shell: C:\Apps\OctopusDeploy.ps1
    args:
      creates: C:\Octopus
    register: deploy_server

  - debug:
      msg: "{{deploy_server}}"

  - name: Copy Octopus API Key Create Script
    win_template:
      src: ApiKey.ps1
      dest: C:\Apps\ApiKey.ps1

  - name: Create API key
    win_shell: C:\Apps\ApiKey.ps1
    register: api_key

  - debug:
      msg: "{{api_key}}"

  - name: Copy Octopus Environment Create Script
    win_template:
      src: OctopusEnvironment.ps1
      dest: C:\Apps\OctopusEnvironment.ps1

  - name: Create Environment
    win_shell: C:\Apps\OctopusEnvironment.ps1
    register: create_environment

  - debug:
      msg: "{{create_environment}}"

  - name: Copy Octopus Tentacle Install Script
    win_template:
      src: OctopusTentacle.ps1
      dest: C:\Apps\OctopusTentacle.ps1

  - name: Install Tentacle
    win_shell: C:\Apps\OctopusTentacle.ps1
    args:
      creates: C:\Octopus\Applications
    register: create_tentacle

  - debug:
      msg: "{{create_tentacle}}"