---
- name: Install Octopus MSI
  win_package:
    path: https://s3.amazonaws.com/bamboo-support/Octopus.4.0.0-frontend-refact14728-x64.msi
    state: present
    product_id: "{1D465F9B-FBF1-4ACF-B95C-5612D72F8125}"
    arguments: /quiet RUNMANAGERONEXIT=no

- name: Install Octopus Deploy Server
  win_shell: C:\Apps\OctopusDeploy.ps1