---
- name: Install Octopus MSI
  win_package:
    path: "{{upgrade_msi}}"
    state: present
    product_id: "{{upgrade_id}}"
    arguments: /quiet RUNMANAGERONEXIT=no

- name: Install Octopus Deploy Server
  win_shell: C:\Apps\OctopusDeploy.ps1