---
  - name: Install SDKMAN!
    shell: curl -s http://get.sdkman.io | bash executable=/bin/bash

  - name: download .NET Core
    get_url:
          url: "{{dot_net_download}}"
          dest: /tmp/dotnet.tar.gz
          mode: 0440

  - name: create dotnet directory
    file:
        path: /opt/dotnet
        state: directory

  - name: extract dotnet
    unarchive:
        src: /tmp/dotnet.tar.gz
        dest: /opt/dotnet
        copy: no

  - name: link dotnet
    file:
      src: /opt/dotnet/dotnet
      dest: /usr/local/bin/dotnet
      state: link
