---
  - name: stop tomcat service
    service:
      name: tomcat
      enabled: yes
      state: stopped
    ignore_errors: yes

  - name: kill tomcat
    command: "pkill -9 -U {{tomcat_user}}"
    ignore_errors: yes

  - name: create user to run tomcat
    user: name={{tomcat_user}}

  - name: Add EPEL repository
    yum:
      name: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm
      state: present

  - name: install useful packages
    yum:
      name: wget,elinks,telnet,htop,mlocate,python-pip,vim,nano,jq,java-1.8.0-openjdk-devel,unzip,maven,yum-utils

  - name: install powershell
    yum:
      name: "{{powershell_download}}"

  - name: Set JAVA_HOME
    lineinfile: dest=/etc/environment state=present regexp='^JAVA_HOME' line='JAVA_HOME=/usr/lib/jvm/jre-1.8.0'

  - name: install mono key
    get_url:
        url: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        dest: /tmp/GPG-KEY-mono
        mode: 0440

  - name: import mono key
    rpm_key:
      state: present
      key: /tmp/GPG-KEY-mono

  - name: Add mono repo
    yum_repository:
      name: mono
      description: Mono repository
      baseurl: http://download.mono-project.com/repo/centos7/
      gpgkey: http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
      gpgcheck: yes
      enabled: yes

  - name: install mono
    yum:
      name: mono-devel

  - name: download tomcat
    get_url:
        url: "{{tomcat_download}}"
        dest: /tmp/tomcat.tar.gz
        mode: 0440

  - name: extract tomcat
    unarchive:
        src: /tmp/tomcat.tar.gz
        dest: /opt
        copy: no

  - name: set tomcat users
    template:
      src: tomcat-users.xml
      dest: /opt/apache-tomcat-8.5.15/conf/tomcat-users.xml
      owner: tomcat
      group: tomcat
      mode: 0600

  - name: set tomcat server settings
    template:
      src: server.xml
      dest: /opt/apache-tomcat-8.5.15/conf/server.xml
      owner: tomcat
      group: tomcat
      mode: 0600

  - name: allow manager to be used anywhere
    template:
      src: context.xml
      dest: /opt/apache-tomcat-8.5.15/webapps/manager/META-INF/context.xml
      owner: tomcat
      group: tomcat
      mode: 0600

  - name: install tomcat service
    template:
      src: tomcat
      dest: /etc/init.d/tomcat
      owner: root
      group: root
      mode: 0755

  - name: set tomcat permissions
    file:
      state: directory
      path: /opt/apache-tomcat-8.5.15
      owner: "{{tomcat_user}}"
      group: "{{tomcat_user}}"
      recurse: true

  - name: allow centos user to push to webapps
    file:
      state: directory
      path: /opt/apache-tomcat-8.5.15/webapps
      owner: "centos"
      group: "centos"
      recurse: true
      mode: 0777

  - name: start tomcat service
    service:
      name: tomcat
      enabled: yes
      state: restarted