---
  - include_vars: "{{playbook_dir}}/vars/encrypted.yml"

  - name: stop tomcat service
    service:
      name: "{{tomcat_user}}"
      enabled: yes
      state: stopped
    ignore_errors: yes

  - name: kill tomcat
    command: "pkill -9 -U {{tomcat_user}}"
    ignore_errors: yes

  - name: create user to run tomcat
    user:
      name: "{{tomcat_user}}"

  - name: download tomcat
    get_url:
        url: "{{tomcat_download}}"
        dest: /tmp/tomcat.tar.gz
        mode: 0440

  - name: extract tomcat
    unarchive:
        src: /tmp/tomcat.tar.gz
        dest: /opt
        copy: no

  - name: set tomcat users
    template:
      src: "{{playbook_dir}}/templates/{{tomcat_template_dir}}/tomcat-users.xml"
      dest: "/opt/apache-tomcat-{{tomcat_version}}/conf/tomcat-users.xml"
      owner: "{{tomcat_user}}"
      group: "{{tomcat_user}}"
      mode: 0600

  - name: set tomcat server settings
    template:
      src: "{{playbook_dir}}/templates/{{tomcat_template_dir}}/server.xml"
      dest: "/opt/apache-tomcat-{{tomcat_version}}/conf/server.xml"
      owner: "{{tomcat_user}}"
      group: "{{tomcat_user}}"
      mode: 0600

  - name: allow manager to be used anywhere
    template:
      src: "{{playbook_dir}}/templates/{{tomcat_template_dir}}/context.xml"
      dest: "/opt/apache-tomcat-{{tomcat_version}}/webapps/manager/META-INF/context.xml"
      owner: tomcat
      group: tomcat
      mode: 0600

  - name: install redhat tomcat service
    template:
      src: "{{playbook_dir}}/templates/{{tomcat_template_dir}}/tomcat"
      dest: "/etc/init.d/{{tomcat_user}}"
      owner: root
      group: root
      mode: 0755
    when: '"centos_server" in group_names'

  - name: install debian tomcat service
    template:
      src: "{{playbook_dir}}/templates/tomcat/tomcat-debian"
      dest: "/etc/init.d/{{tomcat_user}}"
      owner: root
      group: root
      mode: 0755
    when: '"ubuntu_server" in group_names'

  - name: set tomcat permissions
    file:
      state: directory
      path: "/opt/apache-tomcat-{{tomcat_version}}"
      owner: "{{tomcat_user}}"
      group: "{{tomcat_user}}"
      recurse: true

  - name: "allow {{ansible_user}} user to push to webapps"
    file:
      state: directory
      path: "/opt/apache-tomcat-{{tomcat_version}}/webapps"
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      recurse: true
      mode: 0777

  - name: start tomcat service
    service:
      name: "{{tomcat_user}}"
      enabled: yes
      state: restarted