---
  - name: Install Slave Service
    win_command: "{{wildfly_install_dir}}\\bin\\service\\service.bat install /jbossuser {{wildfly_admin_user}} /jbosspass {{wildfly_admin_password}} /controller localhost:14490 /startup /name \"{{wildfly_standalone_service}}\""

  - name: Start Standalone Service
    win_service:
      name: "{{wildfly_standalone_service}}"
      state: started
    ignore_errors: yes

  - name: Open Firewall For EAP
    win_shell: "netsh advfirewall firewall add rule name=\"EAP 6\" dir=in action=allow protocol=TCP localport=12580 profile=public"

  - name: Open Firewall For EAP
    win_shell: "netsh advfirewall firewall add rule name=\"EAP 6\" dir=in action=allow protocol=TCP localport=12943 profile=public"

  - name: Open Firewall For EAP
    win_shell: "netsh advfirewall firewall add rule name=\"EAP 6\" dir=in action=allow protocol=TCP localport=13990 profile=public"

  - name: Add WildFly Shortcut
    win_shortcut:
      src: '%PROGRAMFILES(x86)%\Google\Chrome\Application\chrome.exe'
      dest: '%PUBLIC%\Desktop\EAP 6 Standalone.lnk'
      args: '--new-window http://localhost:12580/'
      directory: '%PROGRAMFILES(x86)%\Google\Chrome\Application'
      icon: '%PROGRAMFILES(x86)%\Google\Chrome\Application\chrome.exe,0'

  - name: Add WildFly Shortcut
    win_shortcut:
      src: '%PROGRAMFILES(x86)%\Google\Chrome\Application\chrome.exe'
      dest: '%PUBLIC%\Desktop\EAP 6 Standalone HTTPS.lnk'
      args: '--new-window https://localhost:12943/'
      directory: '%PROGRAMFILES(x86)%\Google\Chrome\Application'
      icon: '%PROGRAMFILES(x86)%\Google\Chrome\Application\chrome.exe,0'

  - name: Add WildFly Shortcut
    win_shortcut:
      src: '%PROGRAMFILES(x86)%\Google\Chrome\Application\chrome.exe'
      dest: '%PUBLIC%\Desktop\EAP 6 Standalone Admin.lnk'
      args: '--new-window http://localhost:14490/'
      directory: '%PROGRAMFILES(x86)%\Google\Chrome\Application'
      icon: '%PROGRAMFILES(x86)%\Google\Chrome\Application\chrome.exe,0'
