---
  - name: Configure Mono
    command: "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"

  - name: Configure Mono
    command: "echo \"deb http://download.mono-project.com/repo/ubuntu xenial main\" | tee /etc/apt/sources.list.d/mono-official.list"

  - name: Configure Docker
    command: "apt-key adv --fetch-keys https://download.docker.com/linux/ubuntu/gpg"

  - name: Configure Docker
    command: "add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu zesty stable\""

  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: install useful packages
    apt:
      name: wget,elinks,telnet,htop,mlocate,python-pip,vim,nano,jq,openjdk-8-jdk,unzip,maven,git,patch,zip,libunwind8,libapr1,libapr1-dev,libtcnative-1

  - name: install docker packages
    apt:
      name: apt-transport-https,ca-certificates,curl,software-properties-common,docker-ce

  - name: install Mono
    apt:
      name: mono-complete

  - name: Set JAVA_HOME
    lineinfile: dest=/etc/environment state=present regexp='^JAVA_HOME' line='JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64'
