---
  - name: stop bamboo service
    service:
      name: bamboo
      enabled: yes
      state: stopped
    ignore_errors: yes

  - name: create user to run bamboo
    user: name={{bamboo_user}}

  - name: kill bamboo
    command: "pkill -9 -U {{bamboo_user}}"
    ignore_errors: yes

  - name: download bamboo cli
    get_url:
        url: "{{bamboo_cli_download}}"
        dest: /tmp/atlassian-cli.zip
        mode: 0440

  - name: download octopus cli
    get_url:
        url: "{{octopus_cli_download}}"
        dest: /tmp/octopus-tools.tar.gz
        mode: 0440

  - name: extract bamboo cli
    unarchive:
        src: /tmp/atlassian-cli.zip
        dest: /opt
        copy: no

  - name: create octopus cli directory
    file:
        path: /opt/octocli
        state: directory

  - name: extract octopus cli
    unarchive:
        src: /tmp/octopus-tools.tar.gz
        dest: /opt/octocli
        copy: no

  - name: download maven
    get_url:
       url: "{{maven_download}}"
       dest: /tmp/maven.tar.gz
       mode: 0440

  - name: extract maven cli
    unarchive:
        src: /tmp/maven.tar.gz
        dest: /opt
        copy: no