---
  - name: Install the 'Development tools' package group
    yum:
      name: "@Development tools"
      state: present

  - name: Install python pip and other development libraries
    yum:
      name: python-pip, python-devel, python-lxml, openssl-devel

  - name: Install Ansible and the AWS boto library
    pip:
      name: ansible, boto, boto3, pywinrm
      state: latest

  - name: Creates directory for ansible scripts
    file:
      path: "/var/octopus/scripts"
      state: directory
      owner: "{{ansible_user}}"
      group: "{{ansible_user}}"
      mode: 0775

  - name: Set authorized key
    authorized_key:
      user: "{{ansible_user}}"
      state: present
      key: "{{ lookup('file', 'roles/linux-ansible-target/files/ansible_rsa.pub') }}"