---
  - name: Install the 'Development tools' package group
    yum:
      name: "@Development tools"
      state: present

  - name: Install python pip and other development libraries
    yum:
      name: python-pip, python-devel, python-lxml, openssl-devel

  - name: Install Ansible and the AWS boto library
    pip:
      name: ansible, boto