---
wildfly_install_dir: "C:\\{{wildfly_role}}\\{{wildfly_versioned_dir}}"
wildfly_domain_controller_service: WildFlyDomainController
wildfly_slave_service: WildFlySlave
wildfly_standalone_service: WildFlyStandalone
# TODO: encrypt this?
service_password: Password01!